site_name: 'Ardublockly Documentation'
site_url: http://ardublockly.embeddedlog.com
repo_url: http://github.com/carlosperate/ardublockly/wiki
site_description: Visual programming for Arduino.
site_author: carlosperate
site_dir: ../../docs
docs_dir: 'ardublockly.wiki'
theme: 'readthedocs'

# It is IMPERATIVE to leave this property to the end without anything after it.
# This is because the build file will delete everything after this line and
# replace it with newly generated data.
pages:
- Home: 'home.md'
- Quick Start: 'Quick-Start.md'
- User Guide:
    - Installing Ardublockly: 'Installing-Ardublockly.md'
    - Configure Ardublockly: 'Configure-Ardublockly.md'
    - Arduino Compiler Settings: 'Arduino-Compiler-Settings.md'
- Developer Guide:
    - Building Ardublockly: 'Building-Ardublockly.md'
- FAQs: 'FAQs.md'
- About:
    - About Ardublocly: 'About.md'
    - License: 'License.md'
    - Credits: 'Credits.md'