var Blockly2hook = Blockly2hook || {};
Blockly2hook.LOCALISED_TEXT = {
  translationLanguage: "Fran�ais",
  title: "Blockly2hook",
  blocks: "Blocs",
  /* Menu */
  open: "Ouvrir",
  save: "Enregistrer",
  deleteAll: "Abandonner Tous",
  settings: "",
  documentation: "Documentation",
  reportBug: "",
  examples: "Examples",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  xrplhookBoard: "Carte xrplhook",
  xrplhookBoardDefault: "Carte xrplhook inconnu",
  comPort: "",
  comPortDefault: "",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Langue",
  languageDefault: "Langue inconnu",
  sketchName: "Nom de Sketch",
  /* xrplhook console output */
  xrplhookOpMainTitle: "",
  xrplhookOpWaiting: "",
  xrplhookOpUploadedTitle: "",
  xrplhookOpVerifiedTitle: "",
  xrplhookOpOpenedTitle: "",
  xrplhookOpOpenedBody: "",
  xrplhookOpErrorUpVerTitle: "",
  xrplhookOpErrorSketchTitle: "",
  xrplhookOpErrorFlagTitle: "",
  xrplhookOpErrorFlagPrefTitle: "",
  xrplhookOpErrorIdeDirTitle: "",
  xrplhookOpErrorIdeDirBody: "",
  xrplhookOpErrorIdeOptionTitle: "",
  xrplhookOpErrorIdeOptionBody: "",
  xrplhookOpErrorIdePortTitle: "",
  xrplhookOpErrorIdePortBody: "",
  xrplhookOpErrorIdeBoardTitle: "",
  xrplhookOpErrorIdeBoardBody: "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody: "",
  noServerNoLangBody: "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "",
  uploadSketch: "",
  verifyingSketch: "",
  verifySketch: "",
  openingSketch: "",
  openSketch: "",
  notImplemented: "",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuler",
  return: "Retour",
  /* Cards */
  xrplhookSourceCode: "",
  blocksXml: "Blocs XML",
  /* Toolbox Categories*/
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  catInputOutput: "Entree/Sortie",
  catTime: "Temps",
  catAudio: "Audio",
  catMotors: "Moteurs",
  catComms: "Comms",
};
