var Blockly2hook = Blockly2hook || {};
Blockly2hook.LOCALISED_TEXT = {
  translationLanguage: "Nederlands",
  title: "Blockly2hook",
  blocks: "Blocks",
  /* Menu */
  open: "Open",
  save: "Save",
  deleteAll: "Verwijder Alles",
  settings: "",
  documentation: "Documentatie",
  reportBug: "",
  examples: "Voorbeelden",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  xrplhookBoard: "",
  xrplhookBoardDefault: "",
  comPort: "",
  comPortDefault: "",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Taal",
  languageDefault: "Language onbekend",
  sketchName:  "",
  /* xrplhook console output */
  xrplhookOpMainTitle:  "",
  xrplhookOpWaiting:  "",
  xrplhookOpUploadedTitle:  "",
  xrplhookOpVerifiedTitle:  "",
  xrplhookOpOpenedTitle:  "",
  xrplhookOpOpenedBody:  "",
  xrplhookOpErrorUpVerTitle:  "",
  xrplhookOpErrorSketchTitle:  "",
  xrplhookOpErrorFlagTitle:  "",
  xrplhookOpErrorFlagPrefTitle:  "",
  xrplhookOpErrorIdeDirTitle:  "",
  xrplhookOpErrorIdeDirBody:  "",
  xrplhookOpErrorIdeOptionTitle:  "",
  xrplhookOpErrorIdeOptionBody:  "",
  xrplhookOpErrorIdePortTitle:  "",
  xrplhookOpErrorIdePortBody:  "",
  xrplhookOpErrorIdeBoardTitle:  "",
  xrplhookOpErrorIdeBoardBody:  "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody:  "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "",
  uploadSketch: "",
  verifyingSketch: "",
  verifySketch: "",
  openingSketch: "",
  openSketch: "",
  notImplemented: "",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuleer",
  return: "Terugkeer",
  /* Cards */
  xrplhookSourceCode: "",
  blocksXml: "Blocks XML",
  /* Toolbox Categories*/
  catLogic: "Logica",
  catLoops: "Herhalen",
  catMath: "Wiskunde",
  catText: "Tekst",
  catVariables: "Variabelen",
  catFunctions: "Functies",
  catInputOutput: "In/Output",
  catTime: "Tijd",
  catAudio: "Audio",
  catMotors: "Motoren",
  catComms: "Comms",
};
